This is makeindex, version 2.16 [MiKTeX 24.1].
Scanning style file ./base-redes.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file base-redes.acn....done (14 entries accepted, 0 rejected).
Sorting entries....done (55 comparisons).
Generating output file base-redes.acr....done (19 lines written, 0 warnings).
Output written in base-redes.acr.
Transcript written in base-redes.alg.
